---
pip_install_packages:
  - ansible-lint
  - cryptography
  - django
  - docker
  - flake8
  - jedi
  - jmespath
  - mkdocs
  - neovim
  - powerline-status
  - pylint
  - tmuxp
  - virtualenv
  - virtualenvwrapper
  - yamllint
  - yapf
  - pyvmomi

debian_pip_packages:
  - awscli
  - docker-compose
