---
- name: install ubersicht
  homebrew_cask:
    name: ubersicht
    state: present

- name: install ifstat for network bandwidth
  homebrew:
    name: ifstat
    state: present

- name: Create pecan directory if it doesnt exist
  file:
    path: "{{ widgets_dir }}/pecan"
    state: directory
    owner: "{{ zsh_user }}"
    group: "{{ zsh_user_group }}"
    mode: 0755
    recurse: yes
  tags:
    - initial

- name: write pecan files
  copy:
    src: "{{ item }}"
    dest: "{{ widgets_dir }}/pecan/"
    owner: "{{ zsh_user }}"
    group: "{{ zsh_user_group }}"
  with_fileglob:
    - pecan/*

- name: link pecan widget
  file:
    src: "{{ widgets_dir }}/pecan/pecan-style"
    dest: /usr/local/bin/pecan-style
    state: link

- name: copy pecan ws script file
  template:
    src: ws
    dest: "{{ widgets_dir }}/pecan/scripts/ws"
    mode: 0755

- name: start pecan⁩
  command: pecan-style --load default
  changed_when: false
