- name: Install yabai
  homebrew:
    name: koekeishiya/formulae/yabai
    state: present
    install_options: HEAD
  tags:
  - initial

- name: CodeSign Yabai [Macos]
  command: "codesign -fs 'yabai-cert' /usr/local/bin/yabai"
  changed_when: false
  tags:
  - initial

- name: Install scripting add [Macos]
  command: yabai --install-sa
  changed_when: false
  become: yes
  become_user: root
  tags:
  - initial

- name: Write yabai config
  template:
    src: yabairc
    dest: '{{ dotfiles_user_home }}/.yabairc'
    mode: 0755
  notify: Restart Yabai
  tags:
  - update
