#!/usr/bin/env sh

# bar settings
yabai -m config status_bar                   on
yabai -m config status_bar_text_font         "Hack Nerd Font Mono:Bold:12.0"
yabai -m config status_bar_icon_font         "Hack Nerd Font:Regular:12.0"
yabai -m config status_bar_background_color  0xaa282a36
yabai -m config status_bar_foreground_color  0xffe2e4e5
yabai -m config status_bar_space_icon_strip           
yabai -m config status_bar_power_icon_strip   
yabai -m config status_bar_space_icon        
yabai -m config status_bar_clock_icon        

# global settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          autofocus
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_opacity               on
yabai -m config window_shadow                off
yabai -m config window_border                on
yabai -m config window_border_width          3
yabai -m config active_window_border_color   0xffff6ac1
yabai -m config normal_window_border_color   0xaa282a36
yabai -m config insert_window_border_color   0xffd75f5f
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.90
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  20
yabai -m config bottom_padding               20
yabai -m config left_padding                 20
yabai -m config right_padding                20
yabai -m config window_gap                   10

# window rules
yabai -m rule --add app=Firefox space=1
yabai -m rule --add app=Safari space=1
yabai -m rule --add app=Chrome space=1
yabai -m rule --add app=PyCharm space=3
yabai -m rule --add app=Webstorm space=5
yabai -m rule --add app=Slack space=4
yabai -m rule --add app=Spotify space=6
yabai -m rule --add app="IntelliJ IDEA" space=7
yabai -m rule --add app=RubyMine space=2
yabai -m rule --add app=WebStorm space=9

yabai -m rule --add app="^System Preferences$" manage=off

echo "yabai configuration loaded.."
