#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          autoraise
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_opacity               on
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.95
yabai -m config window_shadow                off
yabai -m config window_border                on
yabai -m config window_border_width          5
yabai -m config active_window_border_color   0xffff6ac1
yabai -m config normal_window_border_color   0xaa282a36
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.90
yabai -m config auto_balance                 on
yabai -m config mouse_modifier                fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  26
yabai -m config bottom_padding               20
yabai -m config left_padding                 20
yabai -m config right_padding                20
yabai -m config window_gap                   10

# window rules
yabai -m rule --add app="^RubyMine$" space=2
yabai -m rule --add app="^JetBrains RubyMine$" space=2
yabai -m rule --add app="^Visual Studio$" space=2
yabai -m rule --add app="^JetBrains Rider$" space=2
yabai -m rule --add app="^Rider$" space=2
yabai -m rule --add app="^WebStorm" space=3
yabai -m rule --add app="^JetBrains PyCharm$" space=5
yabai -m rule --add app="^PyCharm$" space=5
yabai -m rule --add app="^Intelli$" space=6
yabai -m rule --add app="^Slack$" space=4
yabai -m rule --add app="^zoom.us$" space=8
yabai -m rule --add app="^Music$" space=10
yabai -m rule --add app="^Firefox" space=7

# signals
yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"

echo "yabai configuration loaded.."
