# .zshrc config
zsh_editor: nvim
zsh_term: xterm-256color

zsh_debian_path: ${HOME}/bin:/snap/bin

touchpad_speed: .85

brew_prefix: $(brew --prefix)

zsh_mac_path:
- $(ruby -e 'puts Gem.user_dir')/bin
- "{{ brew_prefix }}"
- /opt/local/bin
- /opt/local/sbin

zsh_arch_path:
- /usr/lib/ccache/bin

zsh_path:
- ${ZSH}/bin
- ${HOME}/.local/bin
- ${HOME}/.dotnet/tools
- /usr/local/bin
- /usr/sbin
- /usr/bin
- /sbin
- /bin
- ${ZDOTDIR}/z.sh
- /usr/local/sbin
- ${HOME}/.asdf/asdf.sh
- ${KREW_ROOT:-$HOME/.krew}/bin
- ${GOBIN}

zsh_man_path:
- "{{ brew_prefix }}/share/man"
- "{{ brew_prefix }}/opt/coreutils/libexec/gnuman"
- "{{ brew_prefix }}/opt/findutils/libexec/gnuman"
- "{{ brew_prefix }}/opt/gnu-sed/libexec/gnuman"
- "{{ brew_prefix }}/opt/gnu-tar/libexec/gnuman"
- "{{ brew_prefix }}/opt/grep/libexec/gnuman"

fzf_widgets: ytet5uy4/fzf-widgets
