# .zshrc config
zsh_editor: nvim
zsh_term: xterm-256color

zsh_debian_path: ${HOME}/bin:/snap/bin

touchpad_speed: .85

brew_prefix: $(brew --prefix)

zsh_mac_path:
- $(ruby -e 'puts Gem.user_dir')/bin
- "{{ brew_prefix }}"

zsh_arch_path:
- /usr/lib/ccache/bin

zsh_path:
- ${ZSH}/bin
- ${HOME}/.local/bin
- /usr/local/bin
- /usr/sbin
- /usr/bin
- /sbin
- /bin
- ${ZDOTDIR}/z.sh
- /usr/local/sbin
- ${HOME}/.asdf/asdf.sh
- ${KREW_ROOT:-$HOME/.krew}/bin
- ${HOME}/.local/bin

zsh_man_path:
- "{{ brew_prefix }}/share/man"
- "{{ brew_prefix }}/opt/coreutils/libexec/gnuman"
- "{{ brew_prefix }}/opt/findutils/libexec/gnuman"
- "{{ brew_prefix }}/opt/gnu-sed/libexec/gnuman"
- "{{ brew_prefix }}/opt/gnu-tar/libexec/gnuman"
- "{{ brew_prefix }}/opt/grep/libexec/gnuman"

fzf_widgets: ytet5uy4/fzf-widgets

# Zsh Aliases
zsh_aliases:
### Git ###
- {alias: git, action: hub}
### Bat ###
- {alias: cat, action: bat}
### Exa ###
- {alias: ls, action: 'exa -bh ${${${ABSD#0}:+-G}:---color=auto}'}
- {alias: l, action: ls}
- {alias: l., action: ls -d .*}
- {alias: lA, action: ls -a}
- {alias: la, action: ls -a}
- {alias: ll, action: ls -lbt created}
### Gpg ###
- {alias: gpg, action: gpg2}
### Neovim ###
- {alias: vim, action: nvim}
### Rsync ###
- {alias: rsync, action: noglob rsync --verbose --progress --human-readable --compress
    --archive --hard-links --one-file-system --acls --xattrs}
- {alias: rsync-copy, action: rsync}
- {alias: rsync-move, action: rsync --remove-source-files}
- {alias: rsync-update, action: rsync --update}
- {alias: rsync-synchronize, action: rsync --update --delete}
- {alias: cpv, action: command rsync --}
- {alias: visudo, action: sudo EDITOR=/usr/bin/nvim visudo}

zsh_linux_aliases:
- {alias: apt-update-list-upgrade, action: apt update && apt upgrade --dry-run | grep
    Inst | sort | fzf && apt upgrade}
### Copy ###
- {alias: copy, action: 'xclip -sel clip < $@ '}
- {alias: paste, action: xclip -selection clip -o}
### Lsb ###
- {alias: ubuntu-release, action: lsb_release -a}

### Mac ###
zsh_mac_aliases:
- {alias: cask, action: brew cask}
- {alias: copy, action: pbcopy < $@}
- {alias: paste, action: pbpaste}
- {alias: services, action: brew services}
- {alias: growl, action: terminal-notifier -message}
- {alias: update!, action: sudo softwareupdate -i -a; brew update; brew upgrade; brew
    cleanup; npm update npm -g; npm update -g; sudo gem update --system; sudo gem
    update}
- {alias: cleanup!, action: brew cleanup -s}
- {alias: sleep!, action: pmset sleepnow}
- {alias: hidedesktop, action: defaults write com.apple.finder CreateDesktop -bool
    false && killall Finder}
- {alias: showdesktop, action: defaults write com.apple.finder CreateDesktop -bool
    true && killall Finder}

# zsh_aliases:
zsh_misc_aliases:
- {alias: mkdir, action: mkdir -p}
- {alias: weather, action: 'curl -k4 http://wttr.in/Atlanta'}
- {alias: '......', action: cd ../../../../..}
- {alias: '.....', action: cd ../../../..}
- {alias: '....', action: cd ../../..}
- {alias: '...', action: cd ../..}
- {alias: .., action: cd ..}
- {alias: compfuckyou, action: compaudit | xargs chmod g-w}
- {alias: cputemp, action: sensors | grep Core}
- {alias: find_big_files, action: du -a / | sort -n -r | head -n 10 $1}
- {alias: rd, action: rmdir}
- {alias: suser, action: su -}
- {alias: vlc, action: open -a vlc}
- {alias: week, action: date +%V}
# Flush Directory Service cache
- {alias: flush, action: dscacheutil -flushcache}
- {alias: pcat, action: pygmentize -f terminal256 -O style=native -g}
- {alias: grep, action: grep --color=auto}
- {alias: egrep, action: egrep --color=auto}
- {alias: fgrep, action: fgrep --color=auto}
# remove broken symlinks
- {alias: clsym, action: 'find -L . -name . -o -type d -prune -o -type l -exec rm
    {} +'}
# File Size
- {alias: filesize, action: stat -f \"%z bytes\"}
# ROT13-encode text. Works for decoding, too! ;)
- {alias: rot13, action: tr a-zA-Z n-za-mN-ZA-M}
- {alias: '', action: ''}
### The Rest ###
- {alias: clr, action: clear}
- {alias: pg, action: ps -ef | rg}
- {alias: pkill!, action: 'pkill -9 -f '}
- {alias: fkill, action: fkill -v}
- {alias: lj, action: jobs}
- {alias: reload!, action: . ~/.zshrc}
- {alias: timezsh, action: time zsh -i -c echo}
- {alias: ipe, action: curl ipinfo.io/ip}
- {alias: play, action: ansible-playbook}
- {alias: '', action: ''}

zsh_python_aliases:
- {alias: delete_pycs, action: 'fd . -name \"*.pyc\" -exec rm -rf {} \;'}
- {alias: pyencode, action: 'python -c "import sys, urllib as ul; print ul.quote_plus(sys.argv[1]);"'}
- {alias: py, action: python3}
- {alias: icurl, action: curl -I}
- {alias: pyserv2, action: python2 -m SimpleHTTPServer}
- {alias: pyserv, action: python -m http.server}
- {alias: autopy, action: autopep8 --in-place --aggressive $@}
- {alias: '', action: ''}

zsh_ruby_aliases:
- {alias: urlencode, action: 'ruby -r cgi -e "puts CGI.escape(ARGV[0])"'}
- {alias: urldecode, action: 'ruby -r cgi -e "puts CGI.unescape(ARGV[0])"'}
- {alias: urlencode_json, action: ruby -e "require \"uri\"; puts URI.escape(STDIN.read)"}
- {alias: urldecode_json, action: ruby -e "require \"uri\"; puts URI.unescape(STDIN.read)"}
- {alias: pp_json, action: ruby -e "require \"json\"; require \"yaml\"; puts JSON.parse(STDIN.read).to_yaml"}
- {alias: is_json, action: ruby -e "require \"json\"; begin; JSON.parse(STDIN.read);
    puts true; rescue Exception => e; puts false; end"}
- {alias: '', action: ''}
