# .zshrc config
zsh_editor: nvim
zsh_term: xterm-256color

zsh_debian_path: ${HOME}/bin:/snap/bin

touchpad_speed: .85

zsh_mac_path:
- "{{ brew_prefix }}/bin"
- "{{ brew_prefix }}/sbin"
- $(ruby -e 'puts Gem.user_dir')/bin
- /opt/local/bin
- /opt/local/sbin

zsh_arch_path:
- /usr/lib/ccache/bin

zsh_path:
- /bin
- /usr/local/bin
- /usr/sbin
- /usr/bin
- /sbin
- /usr/local/sbin
- ${GOBIN}
- ${ZSH}/bin
- ${HOME}/.local/bin
- ${HOME}/.dotnet/tools
- ${ZDOTDIR}/z.sh
- "{{ asdf_path }}/asdf.sh"
- ${KREW_ROOT:-$HOME/.krew}/bin

zsh_man_path:
- "{{ brew_prefix }}/share/man"
- "{{ brew_prefix }}/opt/coreutils/libexec/gnuman"
- "{{ brew_prefix }}/opt/findutils/libexec/gnuman"
- "{{ brew_prefix }}/opt/gnu-sed/libexec/gnuman"
- "{{ brew_prefix }}/opt/gnu-tar/libexec/gnuman"
- "{{ brew_prefix }}/opt/grep/libexec/gnuman"

fzf_widgets: ytet5uy4/fzf-widgets
