#!/bin/sh
xrandr --output eDP-1 --primary --mode 2880x1800 --scale 1x1  --pos 0x0 --rotate normal --output HDMI-3 --mode 3440x1440 --pos 2880x0 --scale 1.5x1.5 --rotate normal --output HDMI-2 --off --output HDMI-1 --off --output DP-2 --off --output DP-1 --off
