- name: create (download) directory
  file:
    path: '{{ rubymine_download_dir }}'
    state: directory
    owner: root
    group: root
    mode: 0755
  become: yes
  become_user: root
  tags:
  - configuration

- name: download
  get_url:
    url: '{{ rubymine_mirror }}/{{ rubymine_filename }}'
    dest: '{{ rubymine_download_dir }}/{{ rubymine_filename }}'
    owner: root
    group: root
    mode: 0644
  become: yes
  become_user: root

- name: create rubymine installation directory
  file:
    state: directory
    owner: root
    group: root
    mode: u=rwx,go=rx
    dest: '{{ rubymine_install_dir }}'
  become: yes
  become_user: root

- name: install rubymine
  unarchive:
    src: '{{ rubymine_download_dir }}/{{ rubymine_filename }}'
    remote_src: yes
    extra_opts: --strip-components=1
    dest: '{{ rubymine_install_dir }}'
    owner: root
    group: root
    creates: '{{ rubymine_install_dir }}/bin'
  become: yes
  become_user: root

- name: create bin link
  file:
    src: '{{ rubymine_install_dir }}/bin/rubymine.sh'
    dest: /usr/local/bin/rubymine
    state: link
    owner: root
    group: root
    mode: u=rwx,go=rx
  become: yes
  become_user: root

- name: install rubymine desktop file
  template:
    src: jetbrains-rubymine.desktop.j2
    dest: /usr/share/applications/{{ rubymine_desktop_filename }}
    owner: root
    group: root
    mode: u=rw,go=r
  become: yes
  become_user: root
