#!/usr/bin/env bash

set -e

cp ./themes/developer/style.scss ./scss/style.scss
cp ./themes/developer/colors.scss ./scss/colors.scss

rm -rf ./style.css
sassc --style expanded "./themes/developer/style.scss" >"./style.css" &

# check if ubersicht is running
if pgrep sicht >/dev/null 2>&1; then

  osascript -e 'tell application id "tracesOf.Uebersicht" to refresh'
fi
