---
- name: Install ruby dependencies with homebrew
  homebrew:
    name: "{{ ruby_pkgs }}"
    state: present
  tags:
    - initial

- name: Install python dependencies with homebrew
  homebrew:
    name: "{{ python_pkgs }}"
    state: present
  tags:
    - initial

- name: Install java dependencies with homebrew
  homebrew:
    name: jq
    state: present
  tags:
    - initial
