- name: Install ruby dependencies with homebrew
  community.general.homebrew:
    name: '{{ ruby_pkgs }}'
    state: present
  tags:
  - initial

- name: Install python dependencies with homebrew
  community.general.homebrew:
    name: '{{ python_pkgs }}'
    state: present
  tags:
  - initial

- name: Install java dependencies with homebrew
  community.general.homebrew:
    name: jq
    state: present
  tags:
  - initial

- name: Install asdf
  community.general.homebrew:
    name: asdf
    state: present
  tags:
  - initial
