- name: Install apt items
  package:
    name: '{{ ruby_pkgs }}'
    state: present
  become: yes
  become_user: root
  tags:
  - initial

- name: Install python pkgs for debian
  package:
    name: '{{ python_pkgs }}'
    state: present
  become: yes
  become_user: root
  tags:
  - initial

- name: Install jq for debian
  package:
    name: jq
    state: present
  become: yes
  become_user: root
  tags:
  - initial
