- name: Install python dependencies with homebrew
  community.general.homebrew:
    name: '{{ python_pkgs }}'
    state: present
  tags:
  - initial

- name: Install java dependencies with homebrew
  community.general.homebrew:
    name: jq
    state: present
  tags:
  - initial

- name: Install mise
  community.general.homebrew:
    name: mise
    state: present
  tags:
  - initial
