- name: Install python pkgs for debian
  package:
    name: '{{ python_pkgs }}'
    state: present
  become: true
  become_user: root
  tags:
  - initial

- name: Install jq for debian
  package:
    name: jq
    state: present
  become: true
  become_user: root
  tags:
  - initial

- name: Install mise
  shell: |
    curl https://mise.run | sh
  args:
    creates: '{{ dotfiles_user_home }}/.local/bin/mise'
  become: true
  become_user: '{{ zsh_user }}'
  tags:
  - initial
