plugins:
- itchyny/lightline.vim
- airblade/vim-gitgutter
- artur-shaik/vim-javacomplete2
- bronson/vim-trailing-whitespace
- chriskempson/base16-vim
- ctrlpvim/ctrlp.vim
- edkolev/tmuxline.vim
- hail2u/vim-css3-syntax
- honza/vim-snippets
- junegunn/fzf.vim
- lepture/vim-jinja
- preservim/tagbar
- martinda/Jenkinsfile-vim-syntax
- mboughaba/i3config.vim
- mike-hearn/base16-vim-lightline
- phenomenes/ansible-snippets
- rust-lang/rust.vim
- sbdchd/neoformat
- vim-syntastic/syntastic
- sheerun/vim-polyglot
- Shougo/deol.nvim
- SirVer/ultisnips
- dhruvasagar/vim-open-url
- tmhedberg/SimpylFold
- tmux-plugins/vim-tmux
- tpope/vim-commentary
- tpope/vim-fugitive
- vim-perl/vim-perl
- vim-scripts/groovy.vim
- xolox/vim-misc
- xolox/vim-session
- Yggdroot/indentLine
- davidhalter/jedi-vim
- preservim/nerdtree
- jistr/vim-nerdtree-tabs

extra_plugs:
- {name: fatih/vim-go, extra: "{'do': ':GoInstallBinaries'}"}
- {name: junegunn/fzf, extra: "{ 'dir': '~/.fzf', 'do': './install --all' }"}
- {name: pearofducks/ansible-vim, extra: "{ 'do': 'cd ./UltiSnips; ./generate.py'\
    \ }"}
- {name: raimon49/requirements.txt.vim, extra: "{'for': 'requirements'}"}
- {name: vim-scripts/c.vim, extra: "{'for': ['c', 'cpp']}"}
- {name: neoclide/coc.nvim, extra: "{'branch': 'release'}"}
- {name: dracula/vim, extra: "{ 'as': 'dracula' }"}
