---
pyenv_shell: "{{ pyenv_path }}/bin/pyenv"

pyenv_pkgs:
  - libbz2-dev
  - libffi-dev
  - libncurses5-dev
  - libreadline-dev
  - libsqlite3-dev
  - libssl-dev
  - libxml2-dev
  - libxmlsec1-dev
  - llvm
  - tk-dev
  - xz-utils
  - zlib1g-dev
