- name: update package cache
  pacman:
    upgrade: no
    update_cache: yes
  become: yes
  become_user: root
  tags:
  - update

- name: install packages for makepkg.conf
  package:
    name: pigz
    state: present
  become: yes
  become_user: root
  tags:
  - initial

- name: install packages for makepkg.conf
  package:
    name: lzop
    state: present
  become: yes
  become_user: root
  tags:
  - initial

- name: Write makepkg config
  template:
    src: makepkg.j2
    dest: /etc/makepkg.conf
  become: yes
  become_user: root
  tags:
  - update

- name: Install pacman packages [Archlinux]
  package:
    name: '{{ pacman_packages }}'
    state: present
    update_cache: yes
  become: yes
  become_user: root
  tags:
  - initial

- name: Install sudo for pacman
  pacman:
    name: sudo
    state: present
    update_cache: yes
  become: yes
  become_user: root
  tags:
  - initial
  - sudo

- name: create aur user and give sudo
  user:
    name: '{{ aur_user }}'
    group: wheel
  become: yes
  become_user: root
  tags:
  - initial

- name: Install paru with makepkg
  aur:
    name: paru
    use: makepkg
  tags:
  - initial

- name: upgrade packages [Archlinux]
  pacman:
    upgrade: yes
  become: yes
  become_user: root
  tags:
  - upgrade

- name: install aur packages [Archlinux]
  aur:
    name: '{{ paru_packages }}'
    use: paru
    skip_pgp_check: true
  tags:
  - initial
  - aur_install
