plugins:
- nodejs
- ruby
- python
- golang
- java
- shellcheck

asdf_plugins:
- name: nodejs
  repository: https://github.com/asdf-vm/asdf-nodejs.git
  versions:
  - 16.14.0
  global: 16.14.0
- name: python
  repository: https://github.com/danhper/asdf-python.git
  versions:
  - 3.7.3
  - 3.9.2
  - 3.9.6
  - 3.10.1
  global: 3.10.1
- name: golang
  repository: https://github.com/kennyp/asdf-golang.git
  versions:
  - 1.16.3
  global: 1.16.3
- name: java
  repository: https://github.com/halcyon/asdf-java.git
  versions:
  - zulu-16.28.11
  global: zulu-16.28.11
- name: skaffold
  repository: https://github.com/kristoflemmens/asdf-skaffold.git
  versions:
  - 1.3.1
  global: 1.3.1
- name: shellcheck
  repository: https://github.com/luizm/asdf-shellcheck.git
  versions:
  - 0.7.0
  global: 0.7.0
- name: shfmt
  repository: https://github.com/luizm/asdf-shfmt.git
  versions:
  - 3.0.1
  global: 3.0.1
- name: terraform
  repository: https://github.com/asdf-community/asdf-hashicorp.git
  versions:
  - 0.13.7
  - 1.2.4

asdf_dots:
- {src: default-gems, dest: .default-gems}
- {src: package.json, dest: package.json}
- {src: package-lock.json, dest: package-lock.json}
- {src: asdfrc, dest: .asdfrc}

pip_packages:
- ansible-lint
- cryptography
- django
- docker
- flake8
- jedi
- jmespath
- mkdocs
- neovim
- powerline-status
- pylint
- pyvmomi
- tmuxp
- virtualenv
- virtualenvwrapper
- yamllint
- yapf
- "git+http://github.com/crtomirmajer/secode.git"
