---
- name: create (download) directory
  file:
    path: "{{ webstorm_download_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  become: yes
  become_user: root
  tags:
    - configuration

- name: download
  get_url:
    url: "{{ webstorm_mirror }}/{{ webstorm_filename }}"
    dest: "{{ webstorm_download_dir }}/{{ webstorm_filename }}"
    owner: root
    group: root
    mode: 0644
  become: yes
  become_user: root

- name: create Webstorm installation directory
  file:
    state: directory
    owner: root
    group: root
    mode: 'u=rwx,go=rx'
    dest: '{{ webstorm_install_dir }}'
  become: yes
  become_user: root

- name: install webstorm Professional
  unarchive:
    src: '{{ webstorm_download_dir }}/{{ webstorm_filename }}'
    remote_src: yes
    extra_opts: '--strip-components=1'
    dest: '{{ webstorm_install_dir }}'
    owner: root
    group: root
    creates: '{{ webstorm_install_dir }}/bin'
  become: yes
  become_user: root

- name: create bin link
  file:
    src: '{{ webstorm_install_dir }}/bin/webstorm.sh'
    dest: /usr/local/bin/webstorm
    state: link
    owner: root
    group: root
    mode: 'u=rwx,go=rx'
  become: yes
  become_user: root

- name: install webstorm Professional desktop file
  template:
    src: jetbrains-webstorm.desktop.j2
    dest: '/usr/share/applications/{{ webstorm_desktop_filename }}'
    owner: root
    group: root
    mode: 'u=rw,go=r'
  become: yes
  become_user: root
