---
- name: read vars from first file found, use 'vars/' relative subdir
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - '{{ ansible_facts["os_family"]|lower }}.yml'
        - default.yml
      paths:
        - 'vars'

- name: include os specific tasks
  include_tasks: "{{ ansible_facts['os_family']|lower }}.yml"
  when: "ansible_facts['os_family']|lower is defined"

- name: Install Python interpreters "{{ pyenv_global_versions }}"
  shell: "export PYENV_ROOT={{ pyenv_path }} && export PYTHON_CONFIGURE_OPTS='--enable-shared' && {{ CPPFLAGS }} {{ pyenv_shell }} install {{ item }}"
  args:
    creates: "{{ pyenv_path }}/versions/{{ item }}"
  loop: "{{ pyenv['global_versions'] }}"
  tags:
    - initial

- name: Set global Python versions with pyenv
  copy:
    content: "{% for version in pyenv.global_versions %}{{ version }}\n{% endfor %}"
    dest: "{{ pyenv_path }}/version"
  notify: rehash pyenv
  tags:
    - initial
