- name: include os specific tasks
  include_tasks: "{{ ansible_facts['os_family']|lower }}.yml"
  when: ansible_facts['os_family']|lower is defined

- name: Write screen config
  template:
    src: screen.j2
    dest: '{{ dotfiles_user_home }}/.screenrc'
  tags:
  - update
