- name: include os specific tasks
  include_tasks: "{{ ansible_facts['os_family']|lower }}.yml"
  when: ansible_facts['os_family']|lower is defined

- name: Create neofetch config directory if it doesnt exist
  file:
    path: '{{ dotfiles_user_home }}/.config/neofetch'
    state: directory
    owner: '{{ zsh_user }}'
    group: '{{ zsh_user_group }}'
    mode: 0755
    recurse: yes
  tags:
  - initial

- name: Write neofetch config
  template:
    src: neofetch.j2
    dest: '{{ dotfiles_user_home }}/.config/neofetch/config.conf'
    owner: '{{ zsh_user }}'
    group: '{{ zsh_user_group }}'
  tags:
  - update
