---
- name: Install docker packages [Archlinux]
  package:
    name: docker
    state: present
  become: yes
  become_user: root
  tags:
    - initial

- name: Install docker-compose packages [Archlinux]
  package:
    name: docker-compose
    state: present
  become: yes
  become_user: root
  tags:
    - initial
