- name: Ensure old versions of Docker are not installed.
  package:
    name: '{{ docker_apt_absent_packages }}'
    state: absent
  become: yes
  become_user: root
  tags:
  - initial
  - remove

- name: Add Docker apt key.
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
  register: add_repository_key
  ignore_errors: '{{ docker_apt_ignore_key_error }}'
  become: yes
  become_user: root
  tags:
  - initial

- name: Add Docker repository.
  apt_repository:
    repo: '{{ docker_apt_repository }}'
    state: present
    update_cache: yes
  become: yes
  become_user: root
  tags:
  - initial

- name: Install Docker.
  package:
    name: '{{ docker_packages }}'
    state: '{{ docker_package_state }}'
  notify: restart docker
  become: yes
  become_user: root
  tags:
  - initial
