---
- name: include os specific tasks
  include_tasks: "{{ ansible_facts['os_family']|lower }}.yml"
  when: "ansible_facts['os_family']|lower is defined"

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"
  become: yes
  become_user: root
  when: "ansible_facts['os_family']|lower != 'darwin' "

- name: Ensure docker users are added to the docker group.
  user:
    name: "{{ zsh_user }}"
    groups: docker
    append: yes
  become: yes
  become_user: root
  when: "ansible_facts['os_family']|lower != 'darwin' "
