---
- name: install base-devel
  pacman:
    name: base-devel
    state: present
    update_cache: yes
  become: yes
  become_user: root

- name: install universal ctags
  aur:
    name: universal-ctags-git
    use: yay
  tags:
    - initial
