- name: Import Defaults
  import_tasks: defaults.yml
  tags:
  - defaults

- name: Check that command line tools are installed
  command: /usr/bin/xcode-select -print-path
  register: xcode_select_res
  ignore_errors: true
  changed_when: false
  tags:
  - update

- name: Prepare to install Command Line Tools
  file:
    path: /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
    state: touch
  when: xcode_select_res.stdout|length == 0
  tags:
  - update

- name: Check for Command Line Tools in Software Update list
  shell: |
    set -o pipefail
    softwareupdate -l | grep -B 1 -E "Command Line Tools" | awk -F"*" "/^ +\*/ {print $2}" | sed "s/^ *//" | head -n1
  register: su_list
  when: xcode_select_res.stdout|length == 0
  changed_when: false
  failed_when: su_list.rc != 0 or su_list.stdout|length == 0
  tags:
  - update

- name: Install Command Line Tools
  command: softwareupdate -i "{{ su_list.stdout }}"
  when: xcode_select_res.stdout|length == 0
  notify:
  - Cleanup
  - update

- name: Tap Casks
  homebrew_tap:
    name: "{{ brew_taps }}"
    state: present
  become: no
  tags:
  - brew

- name: Install brew programs
  homebrew:
    name: "{{ brew_packages }}"
    state: present
  become: no
  tags:
  - brew

- name: upgrade brew programs
  homebrew:
    upgrade: yes
  become: no
  tags:
  - upgrade
  - brew

- name: update brew programs
  homebrew:
    upgrade: no
    update_homebrew: yes
  become: no
  tags:
  - update
  - brew

- name: Install Cask Packages
  homebrew_cask:
    name: "{{ brew_casks }}"
    state: present
    accept_external_apps: yes
  tags:
  - cask
  - brew

- name: upgrade Cask programs
  homebrew_cask:
    upgrade: yes
  tags:
  - upgrade
  - brew

- name: shell | make Homebrew shell default
  osx_defaults:
    domain: com.apple.Terminal
    key: Shell
    type: string
    value: /usr/local/bin/zsh
  tags:
  - initial
  - zsh
